/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Number_UInt */

#ifndef _Included_Number_UInt
#define _Included_Number_UInt
#ifdef __cplusplus
extern "C" {
#endif
#undef Number_UInt_serialVersionUID
#define Number_UInt_serialVersionUID -8742448824652078965i64
/*
 * Class:     Number_UInt
 * Method:    toLong
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Number_UInt_toLong
  (JNIEnv *, jclass, jint);

/*
 * Class:     Number_UInt
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Number_UInt_sum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Number_UInt
 * Method:    subtr
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Number_UInt_subtr
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Number_UInt
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Number_UInt_mul
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Number_UInt
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Number_UInt_div
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
